[package]
description = "An abstract of vglang rendering targets."
documentation = "https://docs.rs/vglang-targets"
edition.workspace = true
license = "MIT"
name = "vglang-targets"
repository.workspace = true
version.workspace = true

[dependencies]
vglang-opcode = { workspace = true }
