[package]
description = "A svg target for vglang."
documentation = "https://docs.rs/vglang-svg"
edition.workspace = true
license = "MIT"
name = "vglang-svg"
repository.workspace = true
version.workspace = true

[dependencies]
thiserror = { workspace = true }
xml_dom = { workspace = true }
futures = { workspace = true }
vglang-ir = { workspace = true }
vglang-device = { workspace = true }
