[package]
description = "A utility derive crate for cotati."
documentation = "https://docs.rs/cotati-derive"
edition.workspace = true
license = "MIT"
name = "cotati-derive"
repository.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[features]
dsl = []
