[package]
description = "opcode for vglang device"
documentation = "https://docs.rs/vglang-opcode"
edition.workspace = true
license = "MIT"
name = "vglang-opcode"
repository.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }

[features]
default = ["serde"]
serde = ["dep:serde"]
